// <auto-generated />
using BizCraft.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizCraft.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191019085546_AddedRowTestimonials")]
    partial class AddedRowTestimonials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizCraft.Models.AboutCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("AboutCompanies");

                    b.HasData(
                        new { Id = 1, Icon = "fa fa-bicycle", SubTitle = "Consectetur adipisicing elit sed do eiusmod tempor incididunt ut", Title = "Tons of Features" },
                        new { Id = 2, Icon = "fa fa-diamond", SubTitle = "Proin gravida nibh vel velit auctor Aenean sollicitudin adipisicing", Title = "PowerPack Theme" },
                        new { Id = 3, Icon = "fa fa-street-view", SubTitle = "Simply dummy text and typesettings industry has been the industry", Title = "Day Night Support" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.AboutInfoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("AboutInfoImages");

                    b.HasData(
                        new { Id = 1, Image = "image-block-bg.jpg" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.AwesomeWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("AwesomeWorks");

                    b.HasData(
                        new { Id = 1, Image = "portfolio1.jpg", Title = "Startup Businesse!" },
                        new { Id = 2, Image = "portfolio2.jpg", Title = "Easy to Lanunch" },
                        new { Id = 3, Image = "portfolio3.jpg", Title = "Your Business" },
                        new { Id = 4, Image = "portfolio4.jpg", Title = "Prego Match" },
                        new { Id = 5, Image = "portfolio5.jpg", Title = "Fashion Brand" },
                        new { Id = 6, Image = "portfolio6.jpg", Title = "The Insidage" },
                        new { Id = 7, Image = "portfolio7.jpg", Title = "Light Carpet" },
                        new { Id = 8, Image = "portfolio8.jpg", Title = "Amazing Keyboard" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new { Id = 1, Count = 1200, Title = "Clients" },
                        new { Id = 2, Count = 1277, Title = "Item Sold" },
                        new { Id = 3, Count = 869, Title = "Projects" },
                        new { Id = 4, Count = 76, Title = "Awwards" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new { Id = 1, Icon = "fa fa-heart-o", SubTitle = "Bras urna felis accumsan at ultrde cesid posuere masa socis nautoque penat", Title = "Clean Modern Design" },
                        new { Id = 2, Icon = "fa fa-codepen", SubTitle = "High Life narwhal, banh mi PBR single-origin coffee Odd Future actually aliqua", Title = "Useful Shortcodes" },
                        new { Id = 3, Icon = "fa fa-film", SubTitle = "Consectetur adipisicing elit sed do eiusmod tempor incididunt ut", Title = "Parallax Section" },
                        new { Id = 4, Icon = "fa fa-newspaper-o", SubTitle = "Consectetur adipisicing elit sed do eiusmod tempor incididunt ut", Title = "Multipurpose Concept" },
                        new { Id = 5, Icon = "fa fa-desktop", SubTitle = "Consectetur adipisicing elit sed do eiusmod tempor incididunt ut", Title = "Responsive Layout" },
                        new { Id = 6, Icon = "fa fa-pagelines", SubTitle = "High Life narwhal, banh mi PBR single-origin coffee Odd Future actually aliqua", Title = "Light wight Performance" },
                        new { Id = 7, Icon = "fa fa-whatsapp", SubTitle = "Bras urna felis accumsan at ultrde cesid posuere masa socis nautoque penat", Title = "Free Lifetime Updates" },
                        new { Id = 8, Icon = "fa fa-recycle", SubTitle = "High Life narwhal, banh mi PBR single-origin coffee Odd Future actually aliqua", Title = "Endless Possibilites" },
                        new { Id = 9, Icon = "fa fa-diamond", SubTitle = "Consectetur adipisicing elit sed do eiusmod tempor incididunt ut", Title = "24/7 Live Support" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdWords")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Bandwith")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Cart")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Hosting")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Support")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Pricings");

                    b.HasData(
                        new { Id = 1, AdWords = "$100 Google AdWords", Bandwith = "100GB Monthly Bandwidth", Cart = "SSL Shopping Cart", Hosting = "100 Domain Hosting", Price = "<sup class='currency'>$</sup><strong>49</strong><sub>.99</sub>", Support = "24/7 Live Support", Title = "Basic <small>Monthly plan</small>" },
                        new { Id = 2, AdWords = "$100 Google AdWords", Bandwith = "100GB Monthly Bandwidth", Cart = "SSL Shopping Cart", Hosting = "100 Domain Hosting", Price = "<sup class='currency'>$</sup><strong>99</strong><sub>.99</sub>", Support = "24/7 Live Support", Title = "Standared <small>Monthly plan</small>" },
                        new { Id = 3, AdWords = "$100 Google AdWords", Bandwith = "100GB Monthly Bandwidth", Cart = "SSL Shopping Cart", Hosting = "100 Domain Hosting", Price = "<sup class='currency'>$</sup><strong>149</strong><sub>.99</sub>", Support = "24/7 Live Support", Title = "Professional <small>Monthly plan</small>" },
                        new { Id = 4, AdWords = "$100 Google AdWords", Bandwith = "100GB Monthly Bandwidth", Cart = "SSL Shopping Cart", Hosting = "$100 Google AdWords", Price = "<sup class='currency'>$</sup><strong>399</strong><sub>.99</sub>", Support = "24/7 Live Support", Title = "Premium <small>Monthly plan</small>" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.ServiceProvide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ServiceProvides");

                    b.HasData(
                        new { Id = 1, SubTitle = "High Life narwhal, banh mi PBR single-origin coffee Odd Future actually aliqua polaroid befor", Title = "Web Design" },
                        new { Id = 2, SubTitle = "Food truck master cleanse mixtape minim Portland, cardigan stumptown chambray swag", Title = "Apps Development" },
                        new { Id = 3, SubTitle = "Neutra Thundercats craft beer, listicle meggings bicycle rights 90's XOXO beard cardiga", Title = "eCommerce Websites" },
                        new { Id = 4, SubTitle = "We design beautiful modern engaging websites that always latest responsive technologies.", Title = "Design for Startups" }
                    );
                });

            modelBuilder.Entity("Bizcraft.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ButtonOne");

                    b.Property<string>("ButtonTwo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new { Id = 1, ButtonOne = "Start Now", ButtonTwo = "Learn More", Image = "bg1.jpg", SubTitle = "We Making Difference To Great Things Possible", Title = "Need To Invent The Future!" },
                        new { Id = 2, ButtonTwo = "Take a Tour", Image = "bg2.jpg", SubTitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In consequatur cumque natus!", Title = "How Big Can You Dream?" },
                        new { Id = 3, ButtonOne = "Start", ButtonTwo = "Learn More", Image = "bg3.jpg", SubTitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In consequatur cumque natus!", Title = "Your Challenge is Our Progress" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dribble")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Google")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new { Id = 1, Dribble = "fa fa-dribbble", Facebook = "fa fa-facebook", Google = "fa fa-google-plus", Image = "team1.jpg", Linkedin = "fa fa-linkedin", SubTitle = "Web Designer", Title = "Vosgi Varduhi", Twitter = "fa fa-twitter" },
                        new { Id = 2, Dribble = "fa fa-dribbble", Facebook = "fa fa-facebook", Google = "fa fa-google-plus", Image = "team2.jpg", Linkedin = "fa fa-linkedin", SubTitle = "Web Designer", Title = "Robert Aleska", Twitter = "fa fa-twitter" },
                        new { Id = 3, Dribble = "fa fa-dribbble", Facebook = "fa fa-facebook", Google = "fa fa-google-plus", Image = "team3.jpg", Linkedin = "fa fa-linkedin", SubTitle = "Web Designer", Title = "Taline Voski", Twitter = "fa fa-twitter" },
                        new { Id = 4, Dribble = "fa fa-dribbble", Facebook = "fa fa-facebook", Google = "fa fa-google-plus", Image = "team4.jpg", Linkedin = "fa fa-linkedin", SubTitle = "Web Designer", Title = "Alban Spencer", Twitter = "fa fa-twitter" }
                    );
                });

            modelBuilder.Entity("BizCraft.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new { Id = 1, Image = "testimonial1.jpg", SubTitle = "Lorem Ipsum as their default model text, and a search for ‘lorem ipsum’ will uncover many web sites stil in their infancy.Various versions have evolved over the years, sometimes by accident, sometimes on purpose.Lorem Ipsum is that it as opposed to using.", Title = "Sarah Arevik<span>Chief Executive</span>" },
                        new { Id = 2, Image = "testimonial2.jpg", SubTitle = "Lorem Ipsum as their default model text, and a search for ‘lorem ipsum’ will uncover many web sites stil in their infancy.Various versions have evolved over the years, sometimes by accident, sometimes on purpose.Lorem Ipsum is that it as opposed to using.", Title = "Narek Bedros<span>Sr. Manager</span>" },
                        new { Id = 3, Image = "testimonial3.jpg", SubTitle = "Lorem Ipsum as their default model text, and a search for ‘lorem ipsum’ will uncover many web sites stil in their infancy.Various versions have evolved over the years, sometimes by accident, sometimes on purpose.Lorem Ipsum is that it as opposed to using.", Title = "Taline Lucine<span>Sales Manager</span>" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
